#!/bin/bash

# dive into server source code folder
cd mw/server

# build release executable
cargo build --release

# jump up to root folder
cd ../..

# copy release executable to the root folder level with nice name
cp ./mw/server/target/release/server ./server
